### ISSUE TITLE
Test color in pytest

### ISSUE THREAD

**Issue by romain-navarro38** [DocstringFr/2022-Mentorat-yoyonel-Goban#14]
With pytest, the conclusion of the black_shape_is_not_taken_when_it_has_a_liberty is in red when it is successful and green when it is failed. Very disturbing when you only look at the color 😄

**Comment by yoyonel** [comment]
> With pytest, the conclusion of the black_shape_is_not_taken_when_it_has_a_liberty is in red when it is successful and green when it is failed. Very disturbing when you only look at the color smile

Can you provide an exemple/screenshot/link please ?

**Comment by romain-navarro38** [comment]
Done

![with_marker](https://user-images.githubusercontent.com/97561035/177212879-1c4ca4c4-7192-4f67-8cf0-c09ab7b38f1b.jpg)
![without_marker](https://user-images.githubusercontent.com/97561035/177212882-7392fcca-9777-4b3f-9625-e9c148c96cda.jpg)

**Comment by romain-navarro38** [comment]
With and without the marker @pytest.mark.xfail

**Comment by yoyonel** [comment]
> With and without the marker @pytest.mark.xfail

Not sure to understand what you want/talking about, come to discord to discuss directly about "this" ^^
